# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Karthikeyan Nithiyanandam
title: Senior Java Developer | Solution Architect
email: karthikeyan.ng.jobs@gmail.com
website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: karthikeyan_ng
github_username:  karthikeyan-ng
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: karthikeyan-nithiyanandam
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
xing_username: Karthikeyan_Nithiyanandam2

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello,

  My name's Karthikeyan and I'm a Senior Java developer and Solution Architect.

  I am from Chennai, Tamil Nadu, India. I have 11.8 years of experience in Information and Communication Technology (ICT). I am an enthusiastic developer, passion to do coding by using <mark>Java8+</mark>, <mark>J2EE</mark>, <mark>Spring Ecosystem</mark> and <mark>Open-source</mark> frameworks where I am mainly part of. 
  
  On top of the above said base skills I have also worked in <mark>Microservices architecture</mark> by applying <mark>12 factor application</mark> terminologies. Also, I worked in the following cloud platforms <mark>Pivotal Cloud Foundry (PCF)</mark>, <mark>Azure DevOps (Repos, Pipelines)</mark>, <mark>Amazon Web Services (EC2, S3, BeanStalk, Code Commit, Code Build, Code Deploy, Code Pipeline, Cloud Watch, Lambda, API Gateway)</mark>.

  With more than 10+ years of experience and various tools and technologies I can provide solutions for your business problem as well as mentoring the team members to develop a product or an application. Aspiration to learn Spark, Scala, Kotlin languages in near future. Futuristic vision is to learn AI and ML.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in trending technologies and software engineering some of my other interests and hobbies are:
   - Watching YouTube tech contents and other useful tips and tricks
   - Carrom
   - Listening to Music (Ilayaraja & AR Rahman)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# Dark Mode (true/false/never)
darkmode: true