# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Karthikeyan Nithiyanandam
title: Senior Java Developer | Solution Architect
email: karthikeyan.ng.jobs@gmail.com
website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: karthikeyan_ng
github_username:  karthikeyan-ng
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: chillwildlife
linkedin_username: karthikeyan-nithiyanandam
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
xing_username: Karthikeyan_Nithiyanandam2

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hello,

  My name's Karthikeyan and I'm a Senior Java developer and Solution Architect.

  I am Karthikeyan from Chennai, Tamil Nadu, India. I have 11.8 years of experience in Information and Communication Technology (ICT). I am an enthusiastic developer, passion to do coding by using <mark>Java8+</mark>, <mark>J2EE</mark>, <mark>Spring Ecosystem</mark> and <mark>Open-source frameworks</mark> where I am mainly part of. On top of the above said base skills I have also worked in Microservices architecture by applying 12 factor application terminologies. Also, I worked in the following cloud platforms Pivotal Cloud Foundry (PCF), Azure DevOps (Repos, Pipelines), Amazon Web Services (EC2, S3, BeanStalk, Code Commit, Code Build, Code Deploy, Code Pipeline, Cloud Watch, Lambda, API Gateway).


# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

# Dark Mode (true/false/never)
darkmode: true